# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AniMAT
author: MatAkademiet
#logo: animat-black.png

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
    - sphinx_panels
    - sphinx_autorun
    - sphinx_tippy
  config:
    language: da
    html_theme: sphinx_book_theme
    html_theme_options:
      logo:
        image_light: 'animat-black.png'
        image_dark: 'animat-white.png'
      use_download_button: false
      repository_url: https://github.com/sphinx-doc/sphinx
      use_issues_button: false
      use_repository_button: false
      use_edit_page_button: false
    html_static_path: ['_static']
    html_css_files:
      - 'custom.css'
      - 'custom_proof.css'
      - 'custom_exercise.css'
      - 'custom_panels.css'
      - 'custom_tippy.css'
    tippy_enable_mathjax: true
    tippy_tip_selector: 'figure, table, img, p, aside, div.admonition, div.literal-block-wrapper, div.math'
    html_js_files:
      - 'custom.js'

#html:
#  theme:
#    options:
#      logo:
#        image_light: animat-black.png
#        image_dark: animat-white.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository




